// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: random.proto

#include "random.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

class RandomRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RandomRequest> _instance;
} _RandomRequest_default_instance_;
class RandomResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RandomResponse> _instance;
} _RandomResponse_default_instance_;
static void InitDefaultsRandomRequest_random_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_RandomRequest_default_instance_;
    new (ptr) ::RandomRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RandomRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RandomRequest_random_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRandomRequest_random_2eproto}, {}};

static void InitDefaultsRandomResponse_random_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_RandomResponse_default_instance_;
    new (ptr) ::RandomResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RandomResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RandomResponse_random_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRandomResponse_random_2eproto}, {}};

void InitDefaults_random_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_RandomRequest_random_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RandomResponse_random_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_random_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_random_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_random_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_random_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RandomRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::RandomRequest, size_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RandomResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::RandomResponse, random_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::RandomRequest)},
  { 6, -1, sizeof(::RandomResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_RandomRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_RandomResponse_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_random_2eproto = {
  {}, AddDescriptors_random_2eproto, "random.proto", schemas,
  file_default_instances, TableStruct_random_2eproto::offsets,
  file_level_metadata_random_2eproto, 2, file_level_enum_descriptors_random_2eproto, file_level_service_descriptors_random_2eproto,
};

const char descriptor_table_protodef_random_2eproto[] =
  "\n\014random.proto\"\035\n\rRandomRequest\022\014\n\004size\030"
  "\001 \001(\005\" \n\016RandomResponse\022\016\n\006random\030\001 \001(\0142"
  ">\n\rRandomService\022-\n\010Generate\022\016.RandomReq"
  "uest\032\017.RandomResponse\"\000b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_random_2eproto = {
  false, InitDefaults_random_2eproto, 
  descriptor_table_protodef_random_2eproto,
  "random.proto", &assign_descriptors_table_random_2eproto, 151,
};

void AddDescriptors_random_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_random_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_random_2eproto = []() { AddDescriptors_random_2eproto(); return true; }();

// ===================================================================

void RandomRequest::InitAsDefaultInstance() {
}
class RandomRequest::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RandomRequest::kSizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RandomRequest::RandomRequest()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:RandomRequest)
}
RandomRequest::RandomRequest(const RandomRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  size_ = from.size_;
  // @@protoc_insertion_point(copy_constructor:RandomRequest)
}

void RandomRequest::SharedCtor() {
  size_ = 0;
}

RandomRequest::~RandomRequest() {
  // @@protoc_insertion_point(destructor:RandomRequest)
  SharedDtor();
}

void RandomRequest::SharedDtor() {
}

void RandomRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RandomRequest& RandomRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_RandomRequest_random_2eproto.base);
  return *internal_default_instance();
}


void RandomRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:RandomRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  size_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* RandomRequest::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<RandomRequest*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 size = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_size(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool RandomRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RandomRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 size = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RandomRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RandomRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void RandomRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RandomRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 size = 1;
  if (this->size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->size(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:RandomRequest)
}

::google::protobuf::uint8* RandomRequest::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:RandomRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 size = 1;
  if (this->size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->size(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RandomRequest)
  return target;
}

size_t RandomRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RandomRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 size = 1;
  if (this->size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->size());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RandomRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RandomRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const RandomRequest* source =
      ::google::protobuf::DynamicCastToGenerated<RandomRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RandomRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RandomRequest)
    MergeFrom(*source);
  }
}

void RandomRequest::MergeFrom(const RandomRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RandomRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.size() != 0) {
    set_size(from.size());
  }
}

void RandomRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RandomRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RandomRequest::CopyFrom(const RandomRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RandomRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RandomRequest::IsInitialized() const {
  return true;
}

void RandomRequest::Swap(RandomRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RandomRequest::InternalSwap(RandomRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(size_, other->size_);
}

::google::protobuf::Metadata RandomRequest::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_random_2eproto);
  return ::file_level_metadata_random_2eproto[kIndexInFileMessages];
}


// ===================================================================

void RandomResponse::InitAsDefaultInstance() {
}
class RandomResponse::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RandomResponse::kRandomFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RandomResponse::RandomResponse()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:RandomResponse)
}
RandomResponse::RandomResponse(const RandomResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  random_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.random().size() > 0) {
    random_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.random_);
  }
  // @@protoc_insertion_point(copy_constructor:RandomResponse)
}

void RandomResponse::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_RandomResponse_random_2eproto.base);
  random_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

RandomResponse::~RandomResponse() {
  // @@protoc_insertion_point(destructor:RandomResponse)
  SharedDtor();
}

void RandomResponse::SharedDtor() {
  random_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RandomResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RandomResponse& RandomResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_RandomResponse_random_2eproto.base);
  return *internal_default_instance();
}


void RandomResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:RandomResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  random_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* RandomResponse::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<RandomResponse*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // bytes random = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_random();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool RandomResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RandomResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes random = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_random()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RandomResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RandomResponse)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void RandomResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RandomResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes random = 1;
  if (this->random().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->random(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:RandomResponse)
}

::google::protobuf::uint8* RandomResponse::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:RandomResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes random = 1;
  if (this->random().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->random(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RandomResponse)
  return target;
}

size_t RandomResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RandomResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes random = 1;
  if (this->random().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->random());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RandomResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RandomResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const RandomResponse* source =
      ::google::protobuf::DynamicCastToGenerated<RandomResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RandomResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RandomResponse)
    MergeFrom(*source);
  }
}

void RandomResponse::MergeFrom(const RandomResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RandomResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.random().size() > 0) {

    random_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.random_);
  }
}

void RandomResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RandomResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RandomResponse::CopyFrom(const RandomResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RandomResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RandomResponse::IsInitialized() const {
  return true;
}

void RandomResponse::Swap(RandomResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RandomResponse::InternalSwap(RandomResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  random_.Swap(&other->random_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata RandomResponse::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_random_2eproto);
  return ::file_level_metadata_random_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::RandomRequest* Arena::CreateMaybeMessage< ::RandomRequest >(Arena* arena) {
  return Arena::CreateInternal< ::RandomRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::RandomResponse* Arena::CreateMaybeMessage< ::RandomResponse >(Arena* arena) {
  return Arena::CreateInternal< ::RandomResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
