// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: wrapkeys.proto
#ifndef GRPC_wrapkeys_2eproto__INCLUDED
#define GRPC_wrapkeys_2eproto__INCLUDED

#include "wrapkeys.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

// 声明grpc服务
class WrapKey final {
 public:
  static constexpr char const* service_full_name() {
    return "WrapKey";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Wrap(::grpc::ClientContext* context, const ::Cipher& request, ::Cipher* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Cipher>> AsyncWrap(::grpc::ClientContext* context, const ::Cipher& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Cipher>>(AsyncWrapRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Cipher>> PrepareAsyncWrap(::grpc::ClientContext* context, const ::Cipher& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Cipher>>(PrepareAsyncWrapRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Wrap(::grpc::ClientContext* context, const ::Cipher* request, ::Cipher* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Wrap(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Cipher* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Cipher>* AsyncWrapRaw(::grpc::ClientContext* context, const ::Cipher& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Cipher>* PrepareAsyncWrapRaw(::grpc::ClientContext* context, const ::Cipher& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Wrap(::grpc::ClientContext* context, const ::Cipher& request, ::Cipher* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Cipher>> AsyncWrap(::grpc::ClientContext* context, const ::Cipher& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Cipher>>(AsyncWrapRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Cipher>> PrepareAsyncWrap(::grpc::ClientContext* context, const ::Cipher& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Cipher>>(PrepareAsyncWrapRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Wrap(::grpc::ClientContext* context, const ::Cipher* request, ::Cipher* response, std::function<void(::grpc::Status)>) override;
      void Wrap(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Cipher* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Cipher>* AsyncWrapRaw(::grpc::ClientContext* context, const ::Cipher& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Cipher>* PrepareAsyncWrapRaw(::grpc::ClientContext* context, const ::Cipher& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Wrap_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Wrap(::grpc::ServerContext* context, const ::Cipher* request, ::Cipher* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Wrap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Wrap() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Wrap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Wrap(::grpc::ServerContext* context, const ::Cipher* request, ::Cipher* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWrap(::grpc::ServerContext* context, ::Cipher* request, ::grpc::ServerAsyncResponseWriter< ::Cipher>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Wrap<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Wrap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Wrap() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::Cipher, ::Cipher>(
          [this](::grpc::ServerContext* context,
                 const ::Cipher* request,
                 ::Cipher* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Wrap(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_Wrap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Wrap(::grpc::ServerContext* context, const ::Cipher* request, ::Cipher* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Wrap(::grpc::ServerContext* context, const ::Cipher* request, ::Cipher* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Wrap<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Wrap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Wrap() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Wrap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Wrap(::grpc::ServerContext* context, const ::Cipher* request, ::Cipher* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Wrap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Wrap() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Wrap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Wrap(::grpc::ServerContext* context, const ::Cipher* request, ::Cipher* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWrap(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Wrap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Wrap() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Wrap(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Wrap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Wrap(::grpc::ServerContext* context, const ::Cipher* request, ::Cipher* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Wrap(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Wrap : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Wrap() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::Cipher, ::Cipher>(std::bind(&WithStreamedUnaryMethod_Wrap<BaseClass>::StreamedWrap, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Wrap() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Wrap(::grpc::ServerContext* context, const ::Cipher* request, ::Cipher* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedWrap(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Cipher,::Cipher>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Wrap<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Wrap<Service > StreamedService;
};


#endif  // GRPC_wrapkeys_2eproto__INCLUDED
