// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pbkdf.proto
#ifndef GRPC_pbkdf_2eproto__INCLUDED
#define GRPC_pbkdf_2eproto__INCLUDED

#include "pbkdf.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class PBKDFService final {
 public:
  static constexpr char const* service_full_name() {
    return "PBKDFService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Pbkdf(::grpc::ClientContext* context, const ::PBKDFRequest& request, ::PBKDFResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PBKDFResponse>> AsyncPbkdf(::grpc::ClientContext* context, const ::PBKDFRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PBKDFResponse>>(AsyncPbkdfRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PBKDFResponse>> PrepareAsyncPbkdf(::grpc::ClientContext* context, const ::PBKDFRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PBKDFResponse>>(PrepareAsyncPbkdfRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Pbkdf(::grpc::ClientContext* context, const ::PBKDFRequest* request, ::PBKDFResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Pbkdf(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PBKDFResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PBKDFResponse>* AsyncPbkdfRaw(::grpc::ClientContext* context, const ::PBKDFRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PBKDFResponse>* PrepareAsyncPbkdfRaw(::grpc::ClientContext* context, const ::PBKDFRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Pbkdf(::grpc::ClientContext* context, const ::PBKDFRequest& request, ::PBKDFResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PBKDFResponse>> AsyncPbkdf(::grpc::ClientContext* context, const ::PBKDFRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PBKDFResponse>>(AsyncPbkdfRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PBKDFResponse>> PrepareAsyncPbkdf(::grpc::ClientContext* context, const ::PBKDFRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PBKDFResponse>>(PrepareAsyncPbkdfRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Pbkdf(::grpc::ClientContext* context, const ::PBKDFRequest* request, ::PBKDFResponse* response, std::function<void(::grpc::Status)>) override;
      void Pbkdf(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PBKDFResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::PBKDFResponse>* AsyncPbkdfRaw(::grpc::ClientContext* context, const ::PBKDFRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::PBKDFResponse>* PrepareAsyncPbkdfRaw(::grpc::ClientContext* context, const ::PBKDFRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Pbkdf_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Pbkdf(::grpc::ServerContext* context, const ::PBKDFRequest* request, ::PBKDFResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Pbkdf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Pbkdf() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Pbkdf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pbkdf(::grpc::ServerContext* context, const ::PBKDFRequest* request, ::PBKDFResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPbkdf(::grpc::ServerContext* context, ::PBKDFRequest* request, ::grpc::ServerAsyncResponseWriter< ::PBKDFResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Pbkdf<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Pbkdf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Pbkdf() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::PBKDFRequest, ::PBKDFResponse>(
          [this](::grpc::ServerContext* context,
                 const ::PBKDFRequest* request,
                 ::PBKDFResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Pbkdf(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_Pbkdf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pbkdf(::grpc::ServerContext* context, const ::PBKDFRequest* request, ::PBKDFResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Pbkdf(::grpc::ServerContext* context, const ::PBKDFRequest* request, ::PBKDFResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Pbkdf<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Pbkdf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Pbkdf() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Pbkdf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pbkdf(::grpc::ServerContext* context, const ::PBKDFRequest* request, ::PBKDFResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Pbkdf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Pbkdf() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Pbkdf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pbkdf(::grpc::ServerContext* context, const ::PBKDFRequest* request, ::PBKDFResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPbkdf(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Pbkdf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Pbkdf() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Pbkdf(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Pbkdf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pbkdf(::grpc::ServerContext* context, const ::PBKDFRequest* request, ::PBKDFResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Pbkdf(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Pbkdf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Pbkdf() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::PBKDFRequest, ::PBKDFResponse>(std::bind(&WithStreamedUnaryMethod_Pbkdf<BaseClass>::StreamedPbkdf, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Pbkdf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Pbkdf(::grpc::ServerContext* context, const ::PBKDFRequest* request, ::PBKDFResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPbkdf(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::PBKDFRequest,::PBKDFResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Pbkdf<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Pbkdf<Service > StreamedService;
};


#endif  // GRPC_pbkdf_2eproto__INCLUDED
