// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: digest.proto
#ifndef GRPC_digest_2eproto__INCLUDED
#define GRPC_digest_2eproto__INCLUDED

#include "digest.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

// 计算数据的摘要
//      * 低优先级服务，可用软算法替代
//      * 允许客户端使用流多次传入数据
//      * 服务端在客户端 complete 之后返回最后的计算值
class DigestService final {
 public:
  static constexpr char const* service_full_name() {
    return "DigestService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::DigestRequest>> Digest(::grpc::ClientContext* context, ::DigestResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::DigestRequest>>(DigestRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::DigestRequest>> AsyncDigest(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::DigestRequest>>(AsyncDigestRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::DigestRequest>> PrepareAsyncDigest(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::DigestRequest>>(PrepareAsyncDigestRaw(context, response, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Digest(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::experimental::ClientWriteReactor< ::DigestRequest>* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientWriterInterface< ::DigestRequest>* DigestRaw(::grpc::ClientContext* context, ::DigestResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::DigestRequest>* AsyncDigestRaw(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::DigestRequest>* PrepareAsyncDigestRaw(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientWriter< ::DigestRequest>> Digest(::grpc::ClientContext* context, ::DigestResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::DigestRequest>>(DigestRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::DigestRequest>> AsyncDigest(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::DigestRequest>>(AsyncDigestRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::DigestRequest>> PrepareAsyncDigest(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::DigestRequest>>(PrepareAsyncDigestRaw(context, response, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Digest(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::experimental::ClientWriteReactor< ::DigestRequest>* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientWriter< ::DigestRequest>* DigestRaw(::grpc::ClientContext* context, ::DigestResponse* response) override;
    ::grpc::ClientAsyncWriter< ::DigestRequest>* AsyncDigestRaw(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::DigestRequest>* PrepareAsyncDigestRaw(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Digest_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Digest(::grpc::ServerContext* context, ::grpc::ServerReader< ::DigestRequest>* reader, ::DigestResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Digest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Digest() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Digest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Digest(::grpc::ServerContext* context, ::grpc::ServerReader< ::DigestRequest>* reader, ::DigestResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDigest(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::DigestResponse, ::DigestRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Digest<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Digest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Digest() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackClientStreamingHandler< ::DigestRequest, ::DigestResponse>(
          [this] { return this->Digest(); }));
    }
    ~ExperimentalWithCallbackMethod_Digest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Digest(::grpc::ServerContext* context, ::grpc::ServerReader< ::DigestRequest>* reader, ::DigestResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerReadReactor< ::DigestRequest, ::DigestResponse>* Digest() {
      return new ::grpc::internal::UnimplementedReadReactor<
        ::DigestRequest, ::DigestResponse>;}
  };
  typedef ExperimentalWithCallbackMethod_Digest<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Digest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Digest() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Digest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Digest(::grpc::ServerContext* context, ::grpc::ServerReader< ::DigestRequest>* reader, ::DigestResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Digest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Digest() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Digest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Digest(::grpc::ServerContext* context, ::grpc::ServerReader< ::DigestRequest>* reader, ::DigestResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDigest(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Digest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Digest() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this] { return this->Digest(); }));
    }
    ~ExperimentalWithRawCallbackMethod_Digest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Digest(::grpc::ServerContext* context, ::grpc::ServerReader< ::DigestRequest>* reader, ::DigestResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* Digest() {
      return new ::grpc::internal::UnimplementedReadReactor<
        ::grpc::ByteBuffer, ::grpc::ByteBuffer>;}
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};


#endif  // GRPC_digest_2eproto__INCLUDED
