// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: digest.proto

#include "digest.pb.h"
#include "digest.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* DigestService_method_names[] = {
  "/DigestService/Digest",
};

std::unique_ptr< DigestService::Stub> DigestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DigestService::Stub> stub(new DigestService::Stub(channel));
  return stub;
}

DigestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Digest_(DigestService_method_names[0], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::DigestRequest>* DigestService::Stub::DigestRaw(::grpc::ClientContext* context, ::DigestResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::DigestRequest>::Create(channel_.get(), rpcmethod_Digest_, context, response);
}

void DigestService::Stub::experimental_async::Digest(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::experimental::ClientWriteReactor< ::DigestRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::DigestRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_Digest_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::DigestRequest>* DigestService::Stub::AsyncDigestRaw(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::DigestRequest>::Create(channel_.get(), cq, rpcmethod_Digest_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::DigestRequest>* DigestService::Stub::PrepareAsyncDigestRaw(::grpc::ClientContext* context, ::DigestResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::DigestRequest>::Create(channel_.get(), cq, rpcmethod_Digest_, context, response, false, nullptr);
}

DigestService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DigestService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< DigestService::Service, ::DigestRequest, ::DigestResponse>(
          std::mem_fn(&DigestService::Service::Digest), this)));
}

DigestService::Service::~Service() {
}

::grpc::Status DigestService::Service::Digest(::grpc::ServerContext* context, ::grpc::ServerReader< ::DigestRequest>* reader, ::DigestResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


